name: Backend Deploy to EC2

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            cd /home/ubuntu/ImgBellProject/imgbell

            # Git 업데이트 (로컬 변경사항 무시하고 강제 업데이트)
            git fetch origin
            git reset --hard origin/main || git reset --hard origin/master

            # Gradle 빌드 권한 설정
            chmod +x ./gradlew

            # 백엔드 서비스 재시작
            cd /home/ubuntu/ImgBellProject
            sudo docker-compose stop backend
            sudo docker-compose rm -f backend
            sudo docker-compose build backend
            sudo docker-compose up -d backend
