name: Backend Deploy to EC2

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/ImgBellProject/ImgBell

            # Git 업데이트
            git pull origin main || git pull origin master

            # Gradle 빌드 권한 설정
            chmod +x ./gradlew

            # 백엔드 서비스 재시작
            cd /home/ubuntu/ImgBellProject
            docker-compose stop backend
            docker-compose rm -f backend
            docker-compose build backend
            docker-compose up -d backend

            # 불필요한 이미지 정리
            docker system prune -f
